const GAMMA_BASE = "https://gamma-api.polymarket.com";
export interface GammaMarket { id:string; question:string; conditionId:string; closed:boolean; active:boolean; outcomes:string; outcomePrices:string; volume:string; }
export interface GammaEvent { id:string; slug:string; title:string; description:string; category:string; active:boolean; closed:boolean; volume:number; markets:GammaMarket[]; }
async function fetchEvents(url:string):Promise<GammaEvent[]> { const res=await fetch(url,{cache:"no-store"}); if(!res.ok) throw new Error(`Gamma API error: ${res.status}`); return res.json(); }
export interface PolymarketEventsPage { events:GammaEvent[]; nextCursor:string|null; }
export async function fetchNewTopEvents(afterCursor:string|null):Promise<PolymarketEventsPage>{const p=new URLSearchParams({active:"true",closed:"false",limit:"50"});if(afterCursor)p.set("after_cursor",afterCursor);const r=await fetch(`${GAMMA_BASE}/events/keyset?${p.toString()}`,{cache:"no-store"});if(!r.ok)throw new Error(`Gamma API error: ${r.status}`);const d=await r.json();return{events:Array.isArray(d?.events)?d.events:[],nextCursor:typeof d?.next_cursor==="string"?d.next_cursor:null};}
export function toProxyYesNoMarket(market:GammaMarket,originalEventTitle:string):GammaMarket|null{let o:string[]=[],p:number[]=[];try{o=JSON.parse(market.outcomes);p=JSON.parse(market.outcomePrices).map(Number);}catch{return null;}const x=o.map((outcome,index)=>({outcome,price:p[index]})).filter(i=>i.outcome&&Number.isFinite(i.price));if(x.length<2)return null;x.sort((a,b)=>b.price-a.price);return{...market,question:`Will ${x[0].outcome} win? (from: ${originalEventTitle})`,outcomes:JSON.stringify(["Yes","No"]),outcomePrices:JSON.stringify([x[0].price,x[1].price])};}
export function toBinaryCompatibleMarket(market:GammaMarket,originalEventTitle:string):GammaMarket|null{return getBinaryOutcomePrices(market)?market:toProxyYesNoMarket(market,originalEventTitle);}
export async function fetchRecentlyClosedEvents(limit:number):Promise<GammaEvent[]>{const urls=[`${GAMMA_BASE}/events?closed=true&order=endDate&ascending=false&limit=${limit}`,`${GAMMA_BASE}/events?closed=true&order=updatedAt&ascending=false&limit=${limit}`,`${GAMMA_BASE}/events?closed=true&limit=${limit}`];let e:Error|null=null;for(const u of urls){try{return await fetchEvents(u);}catch(x){e=x instanceof Error?x:new Error("Unknown Gamma API error");}}throw e??new Error("Gamma API error while fetching closed events");}
export async function fetchEventById(id:string):Promise<GammaEvent|null>{const r=await fetch(`${GAMMA_BASE}/events?id=${encodeURIComponent(id)}&limit=1`,{cache:"no-store"});if(!r.ok)return null;const d=await r.json();return Array.isArray(d)&&d.length?d[0]:null;}

/** Map Polymarket metadata/title/description into Preket's fixed categories. */
export function mapCategory(gammaCategory:string,title="",description=""):string{
 const category=(gammaCategory||"").toLowerCase().trim(), text=`${title} ${description}`.toLowerCase();
 if(category.includes("sport"))return"sports"; if(category.includes("crypto")||category.includes("blockchain"))return"crypto"; if(category.includes("politic")||category.includes("election")||category.includes("government"))return"politics"; if(category.includes("tech")||category.includes("science")||category.includes("ai")||category.includes("technology"))return"tech"; if(category.includes("pop")||category.includes("entertain")||category.includes("culture"))return"entertainment"; if(category.includes("finance")||category.includes("financial")||category.includes("market"))return"finance"; if(category.includes("business")||category.includes("economy")||category.includes("economic"))return"business"; if(category.includes("world")||category.includes("international")||category.includes("global"))return"world";
 const rules:Array<[string,RegExp]>=[
 ["sports",/\b(nfl|nba|wnba|nhl|mlb|ncaa|ufc|mma|fifa|soccer|football|basketball|baseball|tennis|golf|boxing|cricket|formula\s*1|f1|racing|match|tournament|league|championship|playoffs?|world series|super bowl|grand prix|olympics?|fc|afc|sc|cf|club|halftime|total corners|goal differential|clean sheets|atp|wta|fight|power slap|dota 2|esports|e-sports|liga mx|lcs|cs2)\b/],
 ["crypto",/\b(bitcoin|btc|ethereum|eth|solana|sol|crypto|cryptocurrency|blockchain|token|memecoin|dogecoin|xrp|bnb|defi|nft|stablecoin|usdc|usdt|pump|cap)\b/],
 ["tech",/\b(ai|artificial intelligence|openai|chatgpt|gpt[- ]?\d|anthropic|claude|gemini|google|apple|microsoft|nvidia|meta|robot|robotics|technology|tech|software|chip|semiconductor|spacex|tesla|quantum computing|iphone|android|rtx\s*\d+|a100|b200|h100|h200|gpu)\b/],
 ["entertainment",/\b(movie|film|music|song|album|actor|actress|celebrity|grammy|oscar|emmy|tv|television|netflix|youtube|streaming|entertainment|box office|concert|engaged|pregnant|relationship|dating|divorce|bar exam|kardashian|big brother)\b/],
 ["finance",/\b(stock|stocks|nasdaq|s&p|dow jones|fed|federal reserve|interest rate|interest rates|inflation|cpi|gdp|recession|treasury|bond yield|unemployment|jobs report|earnings|revenue|ipo|forex|currency|dollar|euro|pound|yen|reserve bank|repo rate|ecb|central bank|home value|housing market|median home)\b/],
 ["business",/\b(business|corporate|merger|acquisition|startup|ceo|company|retail sales|sales forecast|industry|capital|fund wind-down|funding|investment|raises? new capital)\b/],
 ["politics",/\b(president|presidential|election|senate|congress|governor|mayor|democrat|republican|trump|vote|voting|government|prime minister|parliament|cabinet|supreme court|political party|legislation|bill passes|referendum|politics|charges|charged|police commissioner|nuclear deal|sanctions|high representative|member of the national assembly)\b/],
 ["world",/\b(ukraine|russia|israel|iran|china|taiwan|north korea|south korea|gaza|palestine|nato|united nations|war|warfare|ceasefire|invasion|military conflict|geopolitic|international|global|country|earthquake|hurricane|hurricanes|atlantic hurricane|hawaii|el niño|climate|shipping|strait of hormuz)\b/]
 ];
 for(const [name,pattern] of rules)if(pattern.test(text))return name; return"general";
}
export function getBinaryOutcomePrices(market:GammaMarket):{yes:number;no:number}|null{let o:string[]=[],p:number[]=[];try{o=JSON.parse(market.outcomes);p=JSON.parse(market.outcomePrices).map(Number);}catch{return null;}if(o.length!==2)return null;const yi=o.findIndex(x=>x.toLowerCase()==="yes"),ni=o.findIndex(x=>x.toLowerCase()==="no");if(yi===-1||ni===-1)return null;return{yes:p[yi],no:p[ni]};}
