"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { formatUsd } from "@/lib/types";
import { MarketOdds } from "@/components/MarketOdds";
import { probToCents } from "@/lib/market-ui";
import { getMarketPricesFromReserves, maxBetAmount, MAX_BET_USD, quoteBuyFromReserves, quoteSellFromReserves, TRADE_FEE_USD } from "@/lib/market-math";
import { formatShareCount, maxSellInputValue, parseShareInput, roundShares, sharePctOfTotal, sharesInputValue } from "@/lib/shares";
import { Wallet, Zap } from "lucide-react";
type TradeMode="buy"|"sell"; type Outcome="YES"|"NO";
interface BetFormProps{eventId:string;balance:number;yesPool:number;noPool:number;cpmmRy:number;cpmmRn:number;yesCpmmPerPm:number;noCpmmPerPm:number;yesShares:number;noShares:number;onTradeComplete?:()=>Promise<void>|void;}
export function BetForm({eventId,balance,cpmmRy,cpmmRn,yesCpmmPerPm,noCpmmPerPm,yesShares:initialYesShares,noShares:initialNoShares,onTradeComplete}:Omit<BetFormProps,"yesPool"|"noPool">&Partial<Pick<BetFormProps,"yesPool"|"noPool">>){
 const {yesProb,noProb}=getMarketPricesFromReserves(cpmmRy,cpmmRn); const [mode,setMode]=useState<TradeMode>("buy"),[outcome,setOutcome]=useState<Outcome>("YES"),[amount,setAmount]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false); const [yesShares,setYesShares]=useState(initialYesShares),[noShares,setNoShares]=useState(initialNoShares); const router=useRouter(); const supabase=createClient();
 useEffect(()=>{setYesShares(initialYesShares);setNoShares(initialNoShares)},[initialYesShares,initialNoShares]);
 const heldShares=outcome==="YES"?yesShares:noShares, heldCpmmPerPm=outcome==="YES"?yesCpmmPerPm:noCpmmPerPm, betCap=maxBetAmount(balance), quickAmounts=[1,5,10,50,100].filter(a=>a<=betCap);
 async function handleSubmit(e:React.FormEvent){e.preventDefault();setError("");setLoading(true);try{if(mode==="buy"){const n=parseFloat(amount);if(!Number.isFinite(n)||n<1)throw new Error("Minimum buy is $1.00");if(n+TRADE_FEE_USD>balance)throw new Error("Insufficient balance (includes $0.02 fee)");if(n>betCap)throw new Error(`Maximum buy is ${formatUsd(MAX_BET_USD)}`);const {error:rpcError}=await supabase.rpc("place_bet",{p_event_id:eventId,p_outcome:outcome,p_amount_usd:n});if(rpcError)throw rpcError;}else{const n=parseShareInput(amount);if(n<=0)throw new Error("Enter shares to sell");if(n>heldShares+1e-9)throw new Error(`You only hold ${formatShareCount(heldShares)} ${outcome} shares`);const {error:rpcError}=await supabase.rpc("sell_shares",{p_event_id:eventId,p_outcome:outcome,p_shares:n});if(rpcError)throw rpcError;}if(onTradeComplete)await onTradeComplete();router.refresh();setAmount("");}catch(err){setError(err instanceof Error?err.message:"Trade failed");}finally{setLoading(false);}}
 const numVal=mode==="buy"?parseFloat(amount)||0:parseShareInput(amount),validVal=Number.isFinite(numVal)&&numVal>0,buyQuote=validVal&&mode==="buy"?quoteBuyFromReserves(numVal,outcome,cpmmRy,cpmmRn):null,sellQuote=validVal&&mode==="sell"?quoteSellFromReserves(numVal,heldCpmmPerPm,outcome,cpmmRy,cpmmRn):null,displayPrice=mode==="buy"?buyQuote?.ask??(outcome==="YES"?yesProb:noProb):sellQuote?.bid??(outcome==="YES"?yesProb:noProb);
 return <form onSubmit={handleSubmit} className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] overflow-hidden"><div className="border-b border-[var(--card-border)] bg-gradient-to-r from-indigo-950/60 to-transparent px-6 py-4 flex items-center justify-between"><div className="flex items-center gap-2"><Zap className="h-5 w-5 text-yellow-400"/><h3 className="font-bold text-lg">Trade</h3></div><div className="flex items-center gap-1.5 text-sm text-zinc-400"><Wallet className="h-4 w-4"/>{formatUsd(balance)}</div></div><div className="p-6 space-y-5"><div className="grid grid-cols-2 gap-2 p-1 rounded-xl bg-zinc-900 border border-zinc-800">{(["buy","sell"] as const).map(m=><button key={m} type="button" onClick={()=>{setMode(m);setAmount("");setError("")}} className={`py-2.5 rounded-lg text-sm font-bold capitalize transition-all ${mode===m?(m==="buy"?"bg-emerald-600 text-white shadow":"bg-red-600 text-white shadow"):"text-zinc-500 hover:text-white"}`}>{m}</button>)}</div>{error&&<div className="rounded-xl bg-red-500/10 border border-red-500/30 p-3 text-sm text-red-400">{error}</div>}<div className="flex gap-4 text-xs text-zinc-500"><span>Yes held: <strong className="text-emerald-400">{formatShareCount(yesShares)}</strong></span><span>No held: <strong className="text-red-400">{formatShareCount(noShares)}</strong></span></div><MarketOdds yesProb={yesProb} noProb={noProb} selected={outcome} onSelect={setOutcome}/><div><label className="block text-sm font-medium text-zinc-400 mb-2">{mode==="buy"?"Amount (USD)":"Shares to sell"}</label><div className="relative">{mode==="buy"&&<span className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500 font-medium">$</span>}<input type="number" step={mode==="buy"?"0.01":"any"} min={mode==="buy"?"1":"0.000001"} max={mode==="buy"?betCap:heldShares} value={amount} onChange={e=>setAmount(e.target.value)} placeholder={mode==="buy"?"0.00":"0"} required className={`w-full rounded-xl border border-[var(--card-border)] bg-[var(--background)] ${mode==="buy"?"pl-8":"pl-4"} pr-4 py-3 text-lg font-semibold`}/></div></div><div className="rounded-xl bg-zinc-900/80 border border-zinc-800 p-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-zinc-500">{mode==="buy"?"Ask (buy)":"Bid (sell)"}</span><span className={outcome==="YES"?"text-emerald-400 font-bold":"text-red-400 font-bold"}>{outcome} @ {probToCents(displayPrice)}</span></div></div><button type="submit" disabled={loading||(mode==="buy"?balance<1.02:heldShares<=0)} className={`w-full py-4 rounded-xl font-bold text-lg disabled:opacity-40 ${mode==="buy"?(outcome==="YES"?"bg-emerald-600 text-white":"bg-red-600 text-white"):"bg-zinc-700 text-white"}`}>{loading?"Processing...":mode==="buy"?`Buy ${outcome} · ${probToCents(displayPrice)}`:`Sell ${outcome} · ${probToCents(displayPrice)}`}</button></div></form>;
}