import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { syncAndGetProfile } from "@/lib/get-profile";
import { formatUsd } from "@/lib/types";
import { getMarketPricesFromReserves, realVolume, avgCpmmPerPmFromTrades, normalizeReserves, cpmmIsHealthy } from "@/lib/market-math";
import { netPositions } from "@/lib/positions";
import { LiveBetForm } from "@/components/LiveBetForm";
import { EventHero } from "@/components/MarketUI";
import { OutcomeDisplay } from "@/components/OutcomeDisplay";
import { getCategoryMeta } from "@/lib/market-ui";
import { ArrowLeft, Clock, DollarSign, ShieldCheck } from "lucide-react";
export const dynamic = "force-dynamic";
export default async function EventDetailPage({ params }: { params: Promise<{ id: string }> }) {
 const { id } = await params; const supabase = await createClient(); const admin = createAdminClient();
 const { data: event } = await supabase.from("events").select("*").eq("id", id).single(); if (!event) notFound();
 const { data: { user } } = await supabase.auth.getUser(); let balance=0,yesShares=0,noShares=0,yesCpmmPerPm=1,noCpmmPerPm=1;
 if(user?.email){ const profile=await syncAndGetProfile({id:user.id,email:user.email}); balance=Number(profile?.balance_usd??0);
  const {data:trades,error}=await admin.from("bets").select("outcome, trade_type, shares, amount_usd, entry_price, cpmm_per_pm").eq("event_id",id).eq("user_id",user.id).eq("status","active");
  if(error) console.error("[event-position] failed",error.message); const p=netPositions(trades??[]); yesShares=p.yes; noShares=p.no;
  const ry=Number(event.cpmm_ry??500),rn=Number(event.cpmm_rn??500); yesCpmmPerPm=avgCpmmPerPmFromTrades((trades??[]).filter(t=>t.outcome==="YES"),"YES",ry,rn); noCpmmPerPm=avgCpmmPerPmFromTrades((trades??[]).filter(t=>t.outcome==="NO"),"NO",ry,rn);
 }
 const yesPool=Number(event.total_yes_pool),noPool=Number(event.total_no_pool),ryRaw=Number(event.cpmm_ry??yesPool+500),rnRaw=Number(event.cpmm_rn??noPool+500); const healthy=cpmmIsHealthy(ryRaw,rnRaw); const {ry,rn}=normalizeReserves(ryRaw,rnRaw); const {yesProb,noProb}=getMarketPricesFromReserves(ry,rn); const totalPool=realVolume(yesPool,noPool),meta=getCategoryMeta(event.category);
 return <div className="min-h-screen bg-[var(--background)]"><div className="mx-auto max-w-4xl px-4 py-6"><Link href="/events" className="inline-flex items-center gap-1.5 text-sm text-zinc-500 hover:text-white mb-6"><ArrowLeft className="h-4 w-4"/> Back to Markets</Link><EventHero event={event}/><div className="grid grid-cols-3 gap-3 my-6"><StatCard icon={<DollarSign className="h-4 w-4 text-emerald-400"/>} label="Total Volume" value={formatUsd(totalPool)}/><StatCard icon={<span>{meta.emoji}</span>} label="Category" value={meta.label}/><StatCard icon={<Clock className="h-4 w-4 text-blue-400"/>} label="Status" value={event.status}/></div>{event.status==="resolved"&&<div className="rounded-xl border border-emerald-500/40 bg-emerald-500/10 p-5 mb-6 flex gap-3"><ShieldCheck className="h-6 w-6 text-emerald-400"/><div><p className="font-semibold text-emerald-300">Market Resolved</p><p className="text-sm text-emerald-400/80">Winning outcome: <strong className="text-white">{event.winning_outcome}</strong></p></div></div>}{event.status==="cancelled"&&<div className="rounded-xl border border-zinc-600 bg-zinc-800/50 p-5 mb-6"><p className="font-semibold text-zinc-300">Market Cancelled</p><p className="text-sm text-zinc-500">All bets have been refunded.</p></div>}{event.status==="active"&&!healthy&&<div className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 mb-6 text-sm text-amber-200">Market liquidity was reset — quotes use default depth until your next trade syncs reserves.</div>}<div className="grid lg:grid-cols-5 gap-6"><div className="lg:col-span-2 space-y-4">{event.status==="active"&&<div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5"><h2 className="text-sm font-semibold text-zinc-400 uppercase tracking-wider mb-4">Live Odds</h2><OutcomeDisplay yesProb={yesProb} noProb={noProb}/></div>}<div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5 space-y-3"><h2 className="text-sm font-semibold text-zinc-400 uppercase tracking-wider">Pool Breakdown</h2><PoolRow label="Yes pool" amount={yesPool} color="text-emerald-400" barColor="bg-emerald-500" pct={totalPool>0?yesPool/totalPool:.5}/><PoolRow label="No pool" amount={noPool} color="text-red-400" barColor="bg-red-500" pct={totalPool>0?noPool/totalPool:.5}/></div></div><div className="lg:col-span-3">{event.status==="active"&&(user?<LiveBetForm eventId={event.id} balance={balance} yesPool={yesPool} noPool={noPool} cpmmRy={ry} cpmmRn={rn} yesCpmmPerPm={yesCpmmPerPm} noCpmmPerPm={noCpmmPerPm} yesShares={yesShares} noShares={noShares}/>:<div className="rounded-2xl border border-blue-500/30 p-8 text-center">Sign in to trade</div>)}</div></div></div></div>;
}
function StatCard({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-4"><div className="flex items-center gap-1.5 text-zinc-500 text-xs mb-1">{icon}{label}</div><p className="font-bold text-white">{value}</p></div>}
function PoolRow({label,amount,color,barColor,pct}:{label:string;amount:number;color:string;barColor:string;pct:number}){return <div><div className="flex justify-between text-sm mb-1"><span className={color}>{label}</span><span className="text-zinc-400">{formatUsd(amount)}</span></div><div className="h-1.5 rounded-full bg-zinc-800 overflow-hidden"><div className={`h-full ${barColor} rounded-full`} style={{width:`${pct*100}%`}}/></div></div>}
